### ISSUE TITLE
Updating to v3 of SurveyMonkey API

### ISSUE THREAD

**Issue by Bruledamien** [Datahero/node-surveymonkey#6]
Hi, good job with the v2! Are you planning to do the same thing for the v3 of the API ?
Thanks.

**Comment by ibash** [comment]
Hi, currently there is not a plan to build out the V3 api. Are there endpoints in V3 that are not available in V2?

**Comment by alios** [comment]
Yes Endpoints have changed and also the HTTP methods to access them.

Here is a Transitioning document:
http://help.surveymonkey.com/articles/en_US/kb/Transitioning-to-SurveyMonkey-s-v3-API
