### ISSUE TITLE
How do I call the methode getSurveyDetails with Parameters? 

### ISSUE THREAD

**Issue by stachrom** [Datahero/node-surveymonkey#9]
Can you make an working Example with parameters for V3 ? 

```
var SurveyMonkeyAPI = require('surveymonkey').SurveyMonkeyAPI;
var accessToken = 'Your SurveyMonkey App Access Token';
var surveyId = 12345423; // my survey ID


try { 
    var api = new SurveyMonkeyAPI(accessToken, { version : 'v3', secure : false });
} catch (error) {
    console.log(error.message);
}

api.getSurveyDetails({survey_id:surveyId},function (error, data) {
    if (error)
        console.log(error);
    else
        console.log(JSON.stringify(data)); // Do something with your data!
});

```
This call ends in  --> https://api.surveymonkey.net/v3/surveys/undefined/details?survey_id=12345423
Instead of --> https://api.surveymonkey.net/v3/surveys/12345423/details

Do I miss something? 

https://github.com/Datahero/node-surveymonkey/blob/master/lib/surveymonkey/SurveyMonkeyAPI_v3.js#L47

**Comment by ibash** [comment]
Looks like there's a bug in the code I merged -- mind jumping back down to the v2 api for the time being?

**Comment by stachrom** [comment]
V2 is not working anymore - surveymonkey is blocking V2.

**Comment by ibash** [comment]
@stachrom just pushed a fix and published -- let me know if it works for you?

**Comment by stachrom** [comment]
This should work - I will test it today and let you know. 

Thanks.
